homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/London
  packages: !include_dir_named packages

frontend:
config:
http: !include includes/http.yaml
updater:
  include_used_components: true
discovery:
conversation:
map:
sun:
wake_on_lan:
system_health:
person:
stream:

logbook: !include includes/logbook.yaml
history: !include includes/history.yaml
recorder: !include includes/recorder.yaml
logger: !include includes/loggers.yaml
influxdb: !include includes/influxdb.yaml

cloud: !include_dir_merge_named includes/cloud/

google: !include includes/google.yaml
group: !include_dir_merge_named includes/group/
zwave: !include includes/zwave.yaml
ifttt: !include includes/ifttt.yaml
notify: !include_dir_list includes/notify/
light: !include_dir_merge_list includes/light/
automation: !include_dir_list includes/automation/
media_player: !include_dir_list includes/media_player/
panel_custom: !include_dir_list includes/panel_custom/
script: !include_dir_named includes/script/
