homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:
config:
http:
updater:
  include_used_components: true
discovery:
conversation:
history:
logbook:
map:
cloud:
cast:
sonos:

media_player:
  - platform: plex

mqtt:
  broker: core-mosquitto

recorder:
  db_url: !secret db_url

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://192.168.1.222:9541