homeassistant:
  packages: !include_dir_named packages

default_config:
frontend:
config:
http: !include includes/http.yaml
updater:
  include_used_components: true
discovery:
conversation:
map:
sun:
wake_on_lan:
system_health:
person:
stream:
media_extractor:

logbook: !include includes/logbook.yaml
history: !include includes/history.yaml
recorder: !include includes/recorder.yaml
logger: !include includes/loggers.yaml
influxdb: !include includes/influxdb.yaml

google: !include includes/google.yaml
group: !include_dir_merge_named includes/group/
ifttt: !include includes/ifttt.yaml
notify: !include_dir_list includes/notify/
light: !include_dir_merge_list includes/light/
automation: !include_dir_list includes/automation/
panel_custom: !include_dir_list includes/panel_custom/
script: !include_dir_named includes/script/

homeconnect:
  client_id: !secret homeconnect_client_id
  client_secret: !secret homeconnect_client_secret
