homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/London
  packages: !include_dir_named packages

frontend:
config:
http: !include includes/http.yaml
updater:
  include_used_components: true
discovery:
conversation:
history:
logbook:
map:
cloud:

mqtt: !include includes/mqtt.yaml
recorder: !include includes/recorder.yaml
influxdb: !include includes/influxdb.yaml
google: !include includes/google.yaml
panel_iframe: !include includes/iframe.yaml
nest: !include includes/nest.yaml
tado: !include includes/tado.yaml
duckdns: !include includes/duckdns.yaml
logger: !include includes/loggers.yaml
group: !include_dir_merge_named includes/group/
zwave: !include includes/zwave.yaml
ifttt: !include includes/ifttt.yaml
notify: !include_dir_list includes/notify/
light: !include_dir_merge_list includes/light/
